export const USERS_REPOSITORY = 'USERS_REPOSITORY';
export const TRAININGS_REPOSITORY = 'TRAINING_REPOSITORY';
export const EXERCISES_REPOSITORY = 'EXERCISES_REPOSITORY';
export const EXERCISES_IN_TRAININGS = 'EXERCISES_IN_TRAININGS_REPOSITORY';
export const DONE_EXERCISES = 'DONE_EXERCISES';
export const DATA_SOURCE = 'DATA_SOURCE';
